GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/63de73ae15bd1330a08468d2

###
DELETE http://localhost:3001/api/persons/63df2625f4a7973dc7206b5f

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name" : "Ra",
    "number" : "120-0999-98234"
}

###
PUT http://localhost:3001/api/persons/63df428cd98c42ebb7a27f90
Content-Type: application/json

{
    "name" : "Ra",
    "number" : "120-newNum-98234"
}

